services:
  ET-DB:
    image: thesauravpoddar/expauthdb
    container_name: et-uas-db
    ports:
      - "27018:27017"
    networks:
      - backend

  et-uas:
    image: thesauravpoddar/expenseauth
    container_name: et-uas
    ports:
      - "8081:8081"
    depends_on:
      - ET-DB
    networks:
      - backend

  ET-SER-DB:
    image: thesauravpoddar/expserdb
    container_name: et-ser-db
    ports:
        - "27019:27017"
    networks:
        - backend
  ET-SER:
    image: thesauravpoddar/expensemanager
    container_name: et-ser
    ports:
        - "8082:8082"
    depends_on:
        - ET-SER-DB
    networks:
        - backend
  ET-R:
    image: thesauravpoddar/expensereport
    container_name: et-r
    ports:
        - "8083:8083"
    networks:
        - backend


networks:
  backend:
    name: backend
    driver: bridge

