apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: et-db
  name: et-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: et-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: et-db
    spec:
      containers:
        - image: thesauravpoddar/expauthdb
          name: et-uas-db
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
